04 articles
harrycs1/fe-nc-news pull request #2
Opened 2023-12-11 13:59 UTC by harrycs1

2023-12-11 14:48 UTC, nc-verity-gregory requested changes
Currently there is nothing rendering for / or when I open your app. While it is your choice where articles get rendered, I shouldn't have to manually navigate using the address bar to get around your app.

Looking at the plan you provided you haven't followed it. Why is the data for all articles in app and not in the component that is taking care of articles?

You currently have no loading pattern, on a slow connection the user has no feedback that anything is happening.

On a mobile screen the titles aren't squashed which is nice. Is this all you want to show to the user? A little gap above and below the article card would be ideal for some visual spacing.

There is quite a bit to address here before you move on. Please resubmit when ready.

2023-12-11 14:48 UTC, nc-verity-gregory commented on src/App.jsx
> +      <Routes>
It is not ideal that there is nothing on the route of /. I have to manually navigate to the work you want to show me. This is not a great user experience at all.

2023-12-11 14:48 UTC, nc-verity-gregory commented on src/components/ArticlesList.jsx
> +import Loading from './Loading'
This isn't being used anywhere, on a slow connection I just have a blank screen.

2023-12-11 14:48 UTC, nc-verity-gregory commented on src/App.jsx
> +  const [articles, setArticles] = useState([]);
According to your plan this shouldn't be here. Due to the size of this project, this absolutely shouldn't be here.

2023-12-11 14:48 UTC, nc-verity-gregory commented on src/App.jsx
> +  useEffect(() => {
Any reason the api call for articles is not in the articles component?

2023-12-12 09:03 UTC, nc-poppy-m approved these changes
Good work implementing this feedback! Merge when ready

2023-12-12 09:55 UTC, merged